#!/usr/bin/env bash
# Test: shared/scripts/pdf_audit.py renders a dark-themed HTML report
# with the expected GitHub-dark palette markers, @media print block,
# and every required <section id="..."> — and reports a PDF conversion
# outcome on stdout regardless of whether a headless renderer is present.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=../shared/helpers.sh
source "$SCRIPT_DIR/../shared/helpers.sh"

# ── Sandbox: synthesise a mini Sylph repo layout ─────────────────────
new_sandbox > /dev/null
SBX_PY="$(py_path "$SANDBOX")"

plugins=(
    "boundary-segmenter"
    "branch-workflow"
    "commit-intelligence"
    "sylph-gate"
    "sylph-learning"
    "pr-lifecycle"
    "capability-memory"
)
for p in "${plugins[@]}"; do
    mkdir -p "$SANDBOX/plugins/$p/state"
done

# Seed the same fixture shape as the stats rollup test so we exercise
# every renderer branch (boundaries, branches, commits, gate mix).
cat >"$SANDBOX/plugins/boundary-segmenter/state/metrics.jsonl" <<'JSONL'
{"ts":"2026-04-20T10:00:00Z","event":"post_tool_use","boundary":true,"distance":0.40,"uncertain":false,"seg_exit":0,"path":"src/auth.py"}
{"ts":"2026-04-20T10:05:00Z","event":"post_tool_use","boundary":false,"distance":0.12,"uncertain":false,"seg_exit":0,"path":"src/auth.py"}
{"ts":"2026-04-20T10:10:00Z","event":"post_tool_use","boundary":true,"distance":0.55,"uncertain":true,"seg_exit":0,"path":"src/auth.py"}
{"ts":"2026-04-20T10:15:00Z","event":"post_tool_use","boundary":true,"distance":0.48,"uncertain":false,"seg_exit":0,"path":"docs/README.md"}
JSONL

cat >"$SANDBOX/plugins/branch-workflow/state/metrics.jsonl" <<'JSONL'
{"ts":"2026-04-20T10:01:00Z","event":"w3.boundary.observed","workflow":"github-flow","confidence":0.88}
{"ts":"2026-04-20T10:11:00Z","event":"w3.boundary.observed","workflow":"trunk","confidence":0.71}
JSONL

cat >"$SANDBOX/plugins/commit-intelligence/state/metrics.jsonl" <<'JSONL'
{"ts":"2026-04-20T10:02:00Z","event":"w1.boundary.observed","suggested_type":"feat","cluster_event_count":3}
{"ts":"2026-04-20T10:12:00Z","event":"w1.boundary.observed","suggested_type":"feat","cluster_event_count":4}
{"ts":"2026-04-20T10:16:00Z","event":"w1.boundary.observed","suggested_type":"fix","cluster_event_count":2}
JSONL

cat >"$SANDBOX/plugins/sylph-gate/state/audit.jsonl" <<'JSONL'
{"ts":"2026-04-20T10:03:00Z","decision":"blocked","pattern":"force-push","op":"git push --force","verdict_exit":2,"reason":"protected branch"}
{"ts":"2026-04-20T10:04:00Z","decision":"allowed","pattern":"amend","op":"git commit --amend","verdict_exit":0,"bypass":"--yes-i-know"}
JSONL

cat >"$SANDBOX/plugins/sylph-learning/state/learnings.json" <<'JSONL'
{"schema_version":"1.0","sample_count":12,"confident":true,"signals":{}}
JSONL

# ── Run pdf_audit.py against the sandbox (--no-convert for determinism) ─
out_prefix="$SANDBOX/sylph-audit-test"
out_prefix_py="$(py_path "$out_prefix")"

stdout="$("$PY" "$SHARED_SCRIPTS/pdf_audit.py" \
    --root "$SBX_PY" \
    --period all \
    --out "$out_prefix_py" \
    --no-convert)"

html_path="${out_prefix}.html"
assert_file_exists "$html_path" "HTML report should be written"

# Stdout must clearly communicate the HTML path and PDF-conversion outcome.
assert_contains "$stdout" "HTML report:" "stdout should announce HTML path"
assert_contains "$stdout" "PDF conversion:" "stdout should report PDF conversion status"
ok "pdf_audit --no-convert writes HTML and reports conversion status"

# ── Dark-theme CSS markers ────────────────────────────────────────────
html_body="$(cat "$html_path")"

assert_contains "$html_body" "#0D1117" "dark-theme background (#0D1117) must be present"
assert_contains "$html_body" "#C9D1D9" "dark-theme text colour (#C9D1D9) must be present"
assert_contains "$html_body" "#58A6FF" "dark-theme accent (#58A6FF) must be present"
assert_contains "$html_body" "#30363D" "dark-theme border (#30363D) must be present"
assert_contains "$html_body" "background: #0D1117" "body background rule must use #0D1117"
assert_contains "$html_body" "@media print" "@media print block required for Print-to-PDF fallback"
ok "dark-theme CSS markers present (GitHub dark palette + @media print)"

# ── Structural sections (one per scoped category) ─────────────────────
for sid in summary boundaries branches commits prs gate churn session; do
    assert_contains "$html_body" "<section id=\"$sid\"" "missing <section id=\"$sid\">"
done
ok "all required <section> ids rendered"

# ── Content sanity: rollup numbers flowed through ────────────────────
assert_contains "$html_body" "Sylph Session Audit" "report title must be present"
assert_contains "$html_body" "Generated by Sylph W5" "footer signature must be present"
assert_contains "$html_body" "github-flow" "branch-workflow counts must be rendered"
assert_contains "$html_body" "force-push" "blocked gate category must surface"
assert_contains "$html_body" "src/auth.py" "top-churn file must appear in the report"
ok "rollup + gate fixtures flowed into the rendered HTML"

# ── --convert path: exit 0 even when no headless renderer exists ─────
# Re-run WITHOUT --no-convert; the script must still exit 0 and emit a
# coherent message regardless of whether a PDF was actually produced.
set +e
convert_out="$("$PY" "$SHARED_SCRIPTS/pdf_audit.py" \
    --root "$SBX_PY" \
    --period all \
    --out "$out_prefix_py")"
convert_rc=$?
set -e
assert_exit_code 0 "$convert_rc" "pdf_audit must exit 0 whether PDF converts or not"
assert_contains "$convert_out" "HTML report:" "HTML path still announced on convert run"
assert_contains "$convert_out" "PDF" "PDF outcome (success or fallback) must be reported"
ok "conversion attempt reported and exit code is 0 (best-effort contract)"

# ── Empty root still produces a valid report ─────────────────────────
empty="$SANDBOX/empty-root"
mkdir -p "$empty/plugins"
empty_py="$(py_path "$empty")"
empty_prefix="$SANDBOX/empty-audit"
empty_prefix_py="$(py_path "$empty_prefix")"

"$PY" "$SHARED_SCRIPTS/pdf_audit.py" \
    --root "$empty_py" \
    --period all \
    --out "$empty_prefix_py" \
    --no-convert >/dev/null

assert_file_exists "${empty_prefix}.html" "empty-root run must still render HTML"
empty_body="$(cat "${empty_prefix}.html")"
assert_contains "$empty_body" "<section id=\"summary\"" "summary present even on empty repo"
assert_contains "$empty_body" "#0D1117" "dark theme applied on empty repo too"
ok "empty repo renders a minimal dark-themed report without erroring"
